// SPDX-License-Identifier: CC0-1.0
pragma solidity >=0.8.0;

/// @title ERC-XXXX Encrypted Token Standard
/// @author Kairos Lab (@Valisthea)
/// @notice Standard interface for tokens with FHE-encrypted balances
///         and zero-knowledge transfer verification.

interface IERCXXXX {

    // ─── Custom Errors (OMEGA M-01 fix) ──────────────
    error ProofVerificationFailed(bytes32 proofHash);
    error NonceAlreadyUsed(uint256 nonce);
    error InvalidCiphertext();
    error InsufficientEncryptedBalance();
    error KeyVersionMismatch(uint256 expected, uint256 provided);

    // ─── Events ──────────────────────────────────────
    event BlindTransfer(
        address indexed from,
        address indexed to,
        bytes32 proofHash,
        uint256 keyVersion        // OMEGA L-01 fix: non-indexed, room for metadata
    );
    event BlindApproval(address indexed owner, address indexed spender);
    event BlindMint(address indexed to, bytes32 indexed proofHash);
    event BlindBurn(address indexed from, bytes32 indexed proofHash);
    event KeyRotated(uint256 indexed oldVersion, uint256 indexed newVersion);  // OMEGA C-04 fix

    // ─── ERC-20 Compatible ──────────────────────────
    function name() external view returns (string memory);
    function symbol() external view returns (string memory);
    function decimals() external view returns (uint8);
    function totalSupply() external view returns (uint256);

    // ─── Encrypted Queries ──────────────────────────
    function encryptedBalanceOf(address account) external view returns (bytes memory);
    function encryptionScheme() external view returns (string memory);
    function publicKey() external view returns (bytes memory);
    function keyVersion() external view returns (uint256);          // OMEGA C-04 fix
    function isKeyActive(uint256 version) external view returns (bool); // OMEGA C-04 fix

    // ─── Blind Transfers ────────────────────────────
    function blindTransfer(
        address to,
        bytes calldata encryptedAmount,
        bytes calldata proof
    ) external returns (bool);

    function blindTransferFrom(
        address from,
        address to,
        bytes calldata encryptedAmount,
        bytes calldata proof
    ) external returns (bool);

    // ─── Encrypted Approvals ────────────────────────
    function blindApprove(
        address spender,
        bytes calldata encryptedAmount,
        bytes calldata proof            // Proof: valid ciphertext, non-negative (OMEGA H-01: NO balance check here)
    ) external returns (bool);

    function encryptedAllowance(address owner, address spender)
        external view returns (bytes memory);

    // ─── Selective Disclosure (OPTIONAL) ─────────────
    /// @notice Proof MUST be generated by account owner or authorized delegate.
    ///         Third-party probing is not possible — proof binds to prover identity.
    ///         (OMEGA M-04 clarification)
    function verifyBalancePredicate(
        address account,
        bytes calldata predicate,
        bytes calldata proof
    ) external view returns (bool);

    // ─── Mint / Burn (OPTIONAL) ─────────────────────
    function blindMint(address to, bytes calldata encryptedAmount, bytes calldata proof) external;
    function blindBurn(bytes calldata encryptedAmount, bytes calldata proof) external;
}

/// @title ERC-XXXX Shielded Extension
/// @notice Optional bridge between ERC-20 public pool and encrypted pool
interface IERCXXXX_Shielded is IERCXXXX {        // OMEGA L-03 fix
    event Shielded(address indexed account, uint256 amount);
    event Unshielded(address indexed account, uint256 amount);
    function shield(uint256 amount) external;
    function unshield(uint256 amount, bytes calldata proof) external;
}

/// @title ERC-XXXX Confidential Supply Extension
/// @notice For tokens that hide total supply             // OMEGA C-02 fix
interface IERCXXXX_ConfidentialSupply is IERCXXXX {
    function totalSupplyEncrypted() external view returns (bytes memory);
}

/// @title ERC-XXXX Fee Extension
/// @notice Optional fee interface for FHE computation costs  // OMEGA C-01 fix
interface IERCXXXX_Fees is IERCXXXX {
    event FeeCollected(address indexed payer, address indexed recipient, uint256 amount);
    function feeConfig() external view returns (
        address feeRecipient,
        uint256 feeBasisPoints,
        uint256 pGasPerGate
    );
    function estimateBlindTransferCost() external view returns (uint256 pGas);
}

/// @title ERC-XXXX Batch Extension
/// @notice Batch blind transfers with aggregated proof     // OMEGA M-05 fix
interface IERCXXXX_Batch is IERCXXXX {
    function blindBatchTransfer(
        address[] calldata recipients,
        bytes[] calldata encryptedAmounts,
        bytes calldata batchProof
    ) external returns (bool);
}
